# Generated by Django 4.2 on 2024-10-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('بنزين', 'بنزين'), ('سولار', 'سولار')], max_length=50, verbose_name='نوع الوقود')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='سعر الوقود')),
            ],
            options={
                'verbose_name_plural': 'انواع الوقود',
            },
        ),
        migrations.CreateModel(
            name='Delevry_Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=' المندوب')),
                ('phone', models.CharField(max_length=11, verbose_name=' التليفون')),
            ],
            options={
                'verbose_name_plural': 'مندوب تسليم ',
            },
        ),
        migrations.CreateModel(
            name='Expenses_Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=' المصروف')),
                ('note', models.CharField(default='no-note', max_length=50, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name_plural': 'انواع المصروفات',
            },
        ),
        migrations.CreateModel(
            name='Mission_Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='العملية')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name_plural': 'انواع العمليات',
            },
        ),
    ]
