# Generated by Django 4.2 on 2024-09-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part_Name', models.CharField(max_length=25, unique=True, verbose_name='Part')),
            ],
            options={
                'verbose_name_plural': 'SparePart',
            },
        ),
        migrations.CreateModel(
            name='SpareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30, unique=True, verbose_name='Serial')),
                ('Status_1', models.BooleanField(default=False)),
                ('Status_2', models.BooleanField(default=False)),
                ('Status_3', models.BooleanField(default=False)),
                ('Status_4', models.BooleanField(default=False)),
                ('Status_5', models.BooleanField(default=False)),
                ('Status_6', models.BooleanField(default=False)),
                ('Status_7', models.BooleanField(default=False)),
                ('Status_8', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=50, verbose_name='Note')),
                ('Spare_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareName1', to='Technical.sparename', verbose_name='Spare')),
                ('Spare_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareName2', to='Technical.sparename', verbose_name='Spare')),
                ('Spare_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareName3', to='Technical.sparename', verbose_name='Spare')),
                ('Spare_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareName4', to='Technical.sparename', verbose_name='Spare')),
                ('Spare_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareName5', to='Technical.sparename', verbose_name='Spare')),
                ('Spare_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareName6', to='Technical.sparename', verbose_name='Spare')),
                ('Spare_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareName7', to='Technical.sparename', verbose_name='Spare')),
                ('Spare_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareName8', to='Technical.sparename', verbose_name='Spare')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SpareItem_Product', to='Technical.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='SpareAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SpareAction_Detail', to='Technical.request', verbose_name='Request')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareName', to='Technical.sparename', verbose_name='Spare')),
            ],
        ),
    ]
