# Generated by Django 4.2 on 2024-09-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0002_sparename_action_detail_last_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareaction',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpareItem', to='Technical.spareitem', verbose_name='serial'),
        ),
    ]
