# Generated by Django 4.2 on 2024-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0003_action_detail_last_serial_report_serial_out_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spareaction',
            options={'verbose_name_plural': 'SpareAction'},
        ),
        migrations.AlterModelOptions(
            name='spareitem',
            options={'verbose_name_plural': 'SpareItem'},
        ),
        migrations.AlterField(
            model_name='spareaction',
            name='note',
            field=models.CharField(default='No Note', max_length=50, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='Status_1',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='Status_2',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='Status_3',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='Status_4',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='Status_5',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='Status_6',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='Status_7',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='Status_8',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='note',
            field=models.CharField(default='No Note', max_length=5, verbose_name='Note'),
        ),
    ]
