# Generated by Django 4.2 on 2024-09-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0004_alter_spareaction_options_alter_spareitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_detail',
            name='last_serial',
            field=models.CharField(default='No Serail', max_length=50, verbose_name='last_S.N'),
        ),
        migrations.AddField(
            model_name='request',
            name='branch',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Alex', 'Alex'), ('Asyut', 'Asyut')], default=('Cairo', 'Cairo'), max_length=50, verbose_name='Req_Branch'),
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='note',
            field=models.CharField(default='No Note', max_length=50, verbose_name='Note'),
        ),
    ]
