# Generated by Django 4.2 on 2024-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Details',
            field=models.TextField(max_length=250, verbose_name='FeedBack'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Details',
            field=models.TextField(max_length=250, verbose_name='Details'),
        ),
    ]
