# Generated by Django 4.2 on 2024-10-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0001_initial'),
        ('CRM', '0002_alter_feedback_details_alter_inquiry_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300, unique=True, verbose_name='City')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='file',
            field=models.FileField(default='', max_length=50, upload_to='CRM/Files', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Vendor_Inquiry', to='Technical.vendor'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Inquiry_City', to='CRM.city'),
        ),
    ]
