# Generated by Django 4.2 on 2024-10-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0002_action_detail_created_action_detail_updated_and_more'),
        ('CRM', '0003_city_feedback_file_inquiry_account_inquiry_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cus_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Cus_Service',
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='Cus_Service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Inquiry_Cus_Service', to='Technical.end_user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(max_length=50, upload_to='CRM/Files/<function user_directory at 0x000001587D752200>', verbose_name='File'),
        ),
    ]
