# Generated by Django 4.2 on 2024-10-23 10:14

import CRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_alter_feedback_file_alter_inquiry_cus_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(max_length=50, upload_to=CRM.models.user_directory, verbose_name='File'),
        ),
    ]
