# Generated by Django 4.2 on 2024-10-17 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Technical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Name')),
                ('note', models.CharField(max_length=50, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'EMPLOYEE',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=20, verbose_name='Sales Order')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='No_Note', max_length=150, verbose_name='Note')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Order_Account', to='Technical.vendor', verbose_name='Account')),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, unique=True, verbose_name='Status')),
                ('note', models.CharField(max_length=50, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('phone', models.IntegerField(unique=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('work', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=10)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='No_Note', max_length=150, verbose_name='Note')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Preparing_Author', to='Orders.employee')),
                ('Preparing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Preparing_Status', to='Orders.order_status')),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Receiver_Author', to='Orders.employee')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Order_Status', to='Orders.order_status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Warehouse_Order', to='Orders.order')),
            ],
            options={
                'verbose_name_plural': 'Warehouse',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Order_sales', to='Orders.sales', verbose_name='Sales'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver_QT', models.IntegerField(default=0, verbose_name='Receiver_QT')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('client_QT', models.IntegerField(default=0, verbose_name='Client_QT')),
                ('refund_QT', models.IntegerField(default=0, verbose_name='Refund_QT')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Refund Date')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='No_Note', max_length=150, verbose_name='Note')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Delivery_Author', to='Orders.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Delivery_Order', to='Orders.order')),
            ],
            options={
                'verbose_name_plural': 'Delivery',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Out')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='No_Note', max_length=150, verbose_name='Note')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Coordinator_Status', to='Orders.order_status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Coordinator_Order', to='Orders.order')),
            ],
            options={
                'verbose_name_plural': 'Coordinator',
            },
        ),
    ]
