# Generated by Django 4.2 on 2024-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='note',
            field=models.CharField(default='No_Note', max_length=150, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='order_status',
            name='note',
            field=models.CharField(default='No_Note', max_length=150, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='phone',
            field=models.IntegerField(default='No_Phone', unique=True, verbose_name='Phone'),
        ),
    ]
