# Generated by Django 4.2 on 2024-10-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_employee_note_alter_order_status_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Preparing_Author', to='Orders.employee'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Receiver_Author', to='Orders.employee'),
        ),
    ]
