# Generated by Django 4.2 on 2024-10-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_warehouse_author_alter_warehouse_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(default='no date', verbose_name='Refund Date'),
        ),
    ]
