# Generated by Django 4.2 on 2024-10-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Refund Date'),
        ),
    ]
