# Generated by Django 4.2 on 2024-10-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='client_QT',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='refund_QT',
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_QT', models.IntegerField(default=0, verbose_name='Client_QT')),
                ('refund_QT', models.IntegerField(default=0, verbose_name='Refund_QT')),
                ('collection', models.IntegerField(default=0, verbose_name='Refund_QT')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Refund Date')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='No_Note', max_length=150, verbose_name='Note')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Receiving_Author', to='Orders.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Receiving_Order', to='Orders.order')),
            ],
            options={
                'verbose_name_plural': 'Delivery',
            },
        ),
    ]
