# Generated by Django 4.2 on 2024-10-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_alter_receiving_options_alter_receiving_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='time',
            field=models.TimeField(default='00:00:00', verbose_name='Time'),
        ),
    ]
