# Generated by Django 4.2 on 2024-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_alter_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='time',
            field=models.TimeField(blank=True, default='00:00:00', null=True, verbose_name='Time'),
        ),
    ]
