# Generated by Django 4.2 on 2024-10-21 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_warehouse_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='time',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='time',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='Created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Out'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='Created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
