# Generated by Django 4.2 on 2024-10-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_remove_coordinator_time_remove_warehouse_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Order_Status', to='Orders.order_status'),
        ),
    ]
